In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("georgejdinicola/world-bank-indicators")

print("Path to dataset files:", path)

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading from https://www.kaggle.com/api/v1/datasets/download/georgejdinicola/world-bank-indicators?dataset_version_number=7...

100%|██████████| 50.1M/50.1M [00:07<00:00, 6.78MB/s]

Extracting files...
Path to dataset files: /Users/Martagilant/.cache/kagglehub/datasets/georgejdinicola/world-bank-indicators/versions/7

In [21]:
import pandas as pd
import pathlib

# Path to the downloaded dataset
csv_dir = pathlib.Path("/Users/Martagilant/.cache/kagglehub/datasets/georgejdinicola/world-bank-indicators/versions/7")

# Exclude helper files (optional)
EXCLUDE_FILES = {
    "world-bank-indicator-mapping.csv",
    "world_bank_indicators.csv"
}

# Load all CSVs
csv_paths = sorted(
    p for p in csv_dir.rglob("*.csv")
    if p.name not in EXCLUDE_FILES
)

dfs = []
for path in csv_paths:
    try:
        df = pd.read_csv(path, dtype={"year": "int64", "country": "string"})
        dfs.append(df)
        print(f"Loaded: {path.name}, shape: {df.shape}")
    except Exception as e:
        print(f"Failed to load {path.name}: {e}")

Loaded: agriculture_rural_development.csv, shape: (16611, 25)
Loaded: aid_effectiveness.csv, shape: (11410, 55)
Loaded: climate_change.csv, shape: (16610, 6)
Loaded: economy_growth.csv, shape: (15720, 104)
Loaded: education.csv, shape: (13560, 54)
Loaded: energy_mining.csv, shape: (12513, 16)
Loaded: environment.csv, shape: (16852, 93)
Loaded: external_debt.csv, shape: (8888, 5)
Loaded: financial_sector.csv, shape: (16900, 33)
Loaded: gender.csv, shape: (16884, 73)
Loaded: health.csv, shape: (16845, 146)
Loaded: infrastructure.csv, shape: (15138, 27)
Loaded: poverty.csv, shape: (2426, 8)
Loaded: private_sector.csv, shape: (14470, 50)
Loaded: public_sector.csv, shape: (12163, 46)
Loaded: science_technology.csv, shape: (9888, 10)
Loaded: social_protection_labor.csv, shape: (9288, 32)
Loaded: trade.csv, shape: (14876, 50)
Loaded: urban_development.csv, shape: (16748, 9)

In [22]:
for i, df in enumerate(dfs[:3]):
    print(f"\nDataFrame {i+1}:")
    display(df.head())

DataFrame 1:

,year,country,Fertilizer consumption (% of fertilizer production),Fertilizer consumption (kilograms per hectare of arable land),Agricultural land (sq. km),Agricultural land (% of land area),Arable land (hectares per person),Arable land (% of land area),Land under cereal production (hectares),Permanent cropland (% of land area),...,Livestock production index (2014-2016 = 100),Cereal yield (kg per hectare),"Access to electricity, rural (% of rural population)","Annual freshwater withdrawals, agriculture (% of total freshwater withdrawal)","Agriculture, forestry, and fishing, value added (current US$)","Agriculture, forestry, and fishing, value added (% of GDP)",Rural population,Rural population growth (annual %),Rural population (% of total population),Agricultural raw materials imports (% of merchandise imports)
0,1960,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,27035.0,NaN,49.224000,NaN
1,1960,AFE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,111111891.0,NaN,85.423324,NaN
2,1960,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,8276009.0,NaN,91.599000,NaN
3,1960,AFW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,83269407.0,NaN,85.289994,NaN
4,1960,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4685731.0,NaN,89.565000,NaN

DataFrame 2:

,year,country,"Net bilateral aid flows from DAC donors, Australia (current US$)","Net bilateral aid flows from DAC donors, Austria (current US$)","Net bilateral aid flows from DAC donors, Belgium (current US$)","Net bilateral aid flows from DAC donors, Canada (current US$)","Net bilateral aid flows from DAC donors, European Union institutions (current US$)","Net bilateral aid flows from DAC donors, Switzerland (current US$)","Net bilateral aid flows from DAC donors, Czechia (current US$)","Net bilateral aid flows from DAC donors, Germany (current US$)",...,"Net official flows from UN agencies, UNRWA (current US$)","Net official flows from UN agencies, UNTA (current US$)","Net official flows from UN agencies, UNWTO (current US$)","Net official flows from UN agencies, WFP (current US$)","Net official flows from UN agencies, WHO (current US$)",Net official development assistance and official aid received (current US$),Net official development assistance and official aid received (constant 2021 US$),Net ODA received (% of gross capital formation),Net official development assistance received (constant 2021 US$),"Net ODA received (% of imports of goods, services and primary income)"
0,1960,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.500000e+05,...,NaN,NaN,NaN,NaN,NaN,1.718000e+07,1.201000e+08,19.823067,1.259500e+08,NaN
1,1960,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,-5.000000e+04,-4.000000e+05,NaN,-4.300000e+05,NaN
2,1960,ARE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.100000e+05,4.360000e+06,NaN,4.950000e+06,NaN
3,1960,ARG,NaN,400000.00596,NaN,NaN,NaN,NaN,NaN,1.226000e+07,...,NaN,NaN,NaN,NaN,NaN,4.405000e+07,2.207300e+08,NaN,2.339600e+08,NaN
4,1960,BDI,NaN,NaN,7500000.0,NaN,9999.999776,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,7.530000e+06,7.585000e+07,61.469390,8.122000e+07,NaN

DataFrame 3:

,year,country,Electricity production from natural gas sources (% of total),"Energy use (kg of oil equivalent) per $1,000 GDP (constant 2021 PPP)",Population growth (annual %),"Population, total"
0,1960,ABW,NaN,NaN,NaN,54922.0
1,1960,AFE,NaN,NaN,NaN,130072080.0
2,1960,AFG,NaN,NaN,NaN,9035043.0
3,1960,AFW,NaN,NaN,NaN,97630925.0
4,1960,AGO,NaN,NaN,NaN,5231654.0

In [23]:
df = pd.read_csv(csv_paths[0])
print(csv_paths[0].name)
df.head()

agriculture_rural_development.csv

,year,country,Fertilizer consumption (% of fertilizer production),Fertilizer consumption (kilograms per hectare of arable land),Agricultural land (sq. km),Agricultural land (% of land area),Arable land (hectares per person),Arable land (% of land area),Land under cereal production (hectares),Permanent cropland (% of land area),...,Livestock production index (2014-2016 = 100),Cereal yield (kg per hectare),"Access to electricity, rural (% of rural population)","Annual freshwater withdrawals, agriculture (% of total freshwater withdrawal)","Agriculture, forestry, and fishing, value added (current US$)","Agriculture, forestry, and fishing, value added (% of GDP)",Rural population,Rural population growth (annual %),Rural population (% of total population),Agricultural raw materials imports (% of merchandise imports)
0,1960,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,27035.0,NaN,49.224000,NaN
1,1960,AFE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,111111891.0,NaN,85.423324,NaN
2,1960,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,8276009.0,NaN,91.599000,NaN
3,1960,AFW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,83269407.0,NaN,85.289994,NaN
4,1960,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4685731.0,NaN,89.565000,NaN

In [27]:
dfs = []
for path in csv_paths:
    try:
        df = pd.read_csv(path, dtype={"year": "int64", "country": "string"})
        dfs.append(df)
    except Exception as e:
        print(f"Failed to load {path.name}: {e}")

In [28]:
import pandas as pd
import numpy as np
from functools import reduce
import os

# This assumes `dfs` already contains the 19 loaded dataframes (do NOT redefine dfs = ...)

# Step 1: Check if dfs is valid
if not dfs or not all(isinstance(df, pd.DataFrame) for df in dfs):
    print("❌ ERROR: `dfs` is empty or invalid. Please load the CSVs first.")
else:
    # Step 2: Merge all on year + country
    def merge_dfs(left, right):
        return pd.merge(left, right, on=["year", "country"], how="outer")

    merged = reduce(merge_dfs, dfs)
    merged.replace([np.inf, -np.inf], np.nan, inplace=True)
    merged_cleaned = merged.dropna(axis=1, how='all').dropna(axis=0, how='all')

    # Step 3: Export to src/data_sample
    output_path = "src/data_sample/merged_world_bank_data.csv"
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    merged_cleaned.to_csv(output_path, index=False)
    print(f"✅ Merged CSV saved to: {output_path}")

✅ Merged CSV saved to: src/data_sample/merged_world_bank_data.csv